my_string = input("Сколько символов? ")
print(len(my_string))
print(my_string .upper()) # print(my_string .lower())
print("hi man! how are you?" .replace(" " , ""))
print("hi man! how are you?" .replace("hi man! how are you?", "h"))
print("hi man! how are you?" .replace("hi man! how are you?", "?"))